services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - "5672:5672"
      - "61616:61616"
    volumes:
      - broker:/opt/amq/conf/broker.xml
    environment:
      AMQ_USER: &user "admin"
      AMQ_PASSWORD: &password "admin"
  string_processor:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: nneto/string-processor
    ports:
      - "8080:8080"
    depends_on:
      - artemis
    environment:
      QUARKUS_QPID_JMS_URL: "amqp://artemis:5672"
      QUARKUS_QPID_JMS_USERNAME: *user
      QUARKUS_QPID_JMS_PASSWORD: *password
volumes:
  broker: